import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navebar from "@/components/Navebar";
import LatestTitle from "@/components/LatestTitle";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navebar></Navebar>
        <LatestTitle></LatestTitle>
        <main className="w-7xl mx-auto">
          {children}
          <ToastContainer></ToastContainer>
        </main>
      </body>
    </html>
  );
}
